// ALGORITMA PSEUDECODE

/**
 * STUDY CASE 1
 * 
 * ALGORITMA DAN PSEUDECODE KELILING PERSEGI PANJANG (2*(P+L))
 * 
 * -ALGORITMA
 * 1. MEMBUAT VARIABEL PANJANG
 * 2. MEMBUAT VARIABEL LEBAR
 * 3. MEMBUAT VARIABEL KELILING
 * 4. MASUKKAN RUMUS KELILING = 2 x Panjang + 2 x Lebar
 * 5. TAMPILKAN KELILING PERSEGI PANJANG
 * 
 * -PSEUDECODE
 * 1. STORE PANJANG WITH ANY MEMBER
 * 2. STORE LEBAR WITH ANY MEMBER
 * 3. STORE KELILING WITH 2 MUL PANJANG ADD 2 MUL LEBAR
 * 4. DISPLAY KELILING
 * 
 * STUDY CASE 2
 * 
 * -ALGORITMA
 * 1. CARI LUAS PERMUKAAN TABUNG = 2 x pi x r x r + 2 x pi x r x t
 * 2. MEMBUAT VARIABEL PI
 * 3. MEMBUAT VARIABEL r
 * 4. MEMBUAT VARIABEL t
 * 5. MEMBUAT VARIABEL LUAS PERMUKAAN 
 * 6. ISI LUAS PERMUKAAN DENGAN RUMUS = 2 x pi x r x r + 2 x pi x r x t
 * 7. cetak luasPermukaan
 * 
 * -PSEUDECODE
 * STORE PI WITH 3.14
 * STORE r WITH ANY NUMBER
 * STORE t WITH ANY NUMBER
 * 
 * STORE luasPermukaan WITH 2 MUL PI MUL r MUL r ADD 2 MUL PI MUL r MUL t
 * DISPLAY luasPermukaan
 * 
 * STUDY CASE 3
 * 
 * -ALGORITMA
 * 1. CARI RUMUS VOLUME BOLA = 1/4 x 4/3 x pi x r x r x r
 * 2. buat variabel pi
 * 3. buat variabel r
 * 4. buat variabel volume
 * 5. isi volume dengan rumus = 1/4 x 4/3 x 4/3 x pi x r xr x r
 * 6. cetak volume
 * 
 * -PSEUDECODE
 * STORE PI WITH 3.14
 * STORE r WITH ANY NUMBER
 * 
 * STORE VOLUME WITH 1/4 MUL 4/3 MUL pi MUL r MUL r MUL r
 */