// ALGORITMA PSEUDECODE

/**
 * STUDY CASE 1
 * 
 * ALGORITMA DAN PSEUDECODE KELILING PERSEGI PANJANG (2*(P+L))
 * 
 * -ALGORITMA
 * 1. MEMBUAT VARIABEL PANJANG
 * 2. MEMBUAT VARIABEL LEBAR
 * 3. MEMBUAT VARIABEL KELILING
 * 3. HITUNG KELILING PERSEGI PANJANG DENGAN MENGGUNAKAN RUMUS KELILING = 2*P + 2*L
 * 4. TAMPILKAN KELILING PERSEGI PANJANG
 * 
 * -PSEUDECODE
 * 1. ISI PANJANG DENGAN ANGKA
 * 2. ISI LEBAR DENGAN ANGKA
 * 3. ISI 
 * 
 */